In [1]:
import os

import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [11]:
data = pd.read_csv("data/features-annotated-artistless-with-lyrics-and-languages.csv")
data.head()

# thinking of one hot encoding the nationaility and continent columns and the detected_languages column
# and then applying pca to reduce the dimensionality of the data before fitting gaussians to the artists
nationality_dummies = pd.get_dummies(data['Nationality'], prefix='Nationality')
continent_dummies = pd.get_dummies(data['Continent'], prefix='Continent')
detected_languages_dummies = pd.get_dummies(data['detected_languages'], prefix='detected_languages')
data = pd.concat([data, nationality_dummies, continent_dummies, detected_languages_dummies], axis=1)
data.drop(columns=['Nationality', 'Continent', 'detected_languages'], inplace=True) # drop original columns
data.head()
# write the modified data to a new csv file
#data.to_csv("data/features-annotated-artistless-with-lyrics-and-languages-onehot.csv", index=False)

,id,Rank,Title,Primary Artists,Featuring Artists,Date,Danceability,Energy,Loudness,Speechiness,...,detected_languages_TAGALOG,"detected_languages_TAGALOG, LATIN, ENGLISH, WELSH","detected_languages_TAGALOG, SHONA, SOTHO","detected_languages_TAGALOG, SPANISH, ENGLISH",detected_languages_TSWANA,detected_languages_TURKISH,detected_languages_UKRAINIAN,detected_languages_URDU,detected_languages_VIETNAMESE,detected_languages_WELSH
0,47EiUVwUp4C9fGccaPuUCS,1,dákiti,"bad bunny, jhayco",NaN,26/11/2020,0.731,0.573,-10059.0,0.054,...,0,0,0,0,0,0,0,0,0,0
1,7igeByaBM0MgGsgXtNxDJ7,1,positions,ariana grande,NaN,29/10/2020,0.736,0.802,-4759.0,0.086,...,0,0,0,0,0,0,0,0,0,0
2,3qQbCzHBycnDpGskqOWY0E,1,ella baila sola,"eslabon armado, peso pluma",NaN,29/05/2023,0.668,0.758,-5176.0,0.033,...,0,0,0,0,0,0,0,0,0,0
3,0Yde1VrWbGF2Tus2AQhMuT,1,circles,post malone,NaN,06/09/2019,0.703,0.756,-3407.0,0.038,...,0,0,0,0,0,0,0,0,0,0
4,0TK2YIli7K1leLovkQiNik,1,señorita,"camila cabello, shawn mendes",NaN,25/07/2019,0.759,0.540,-6039.0,0.029,...,0,0,0,0,0,0,0,0,0,0

In [ ]:

artists = os.path.join(os.getcwd(), 'data', 'artists.csv')
artists_df = pd.read_csv(artists)
artists_df.head()

,Artist,Mean Danceability,Std Danceability,Mean Energy,Std Energy,Mean Loudness,Std Loudness,Mean Speechiness,Std Speechiness,Mean Acousticness,Std Acousticness,Mean Instrumentalness,Std Instrumentalness,Mean Valence,Std Valence,Count
0,drake,0.711716,0.151289,0.549638,0.153531,-6402.349258,3444.709399,0.202100,0.140503,0.200074,0.232417,0.010201,0.065975,0.373162,0.208277,229
1,taylor swift,0.592329,0.113179,0.554347,0.175523,-7408.700833,3317.588195,0.064769,0.058960,0.337579,0.326075,0.004301,0.037129,0.392620,0.189788,216
2,future,0.760352,0.123411,0.582162,0.108463,-5987.031508,2562.616316,0.220631,0.119358,0.104190,0.134780,0.004581,0.030612,0.396207,0.210416,179
3,juice wrld,0.667318,0.108455,0.606345,0.123862,-5771.773986,3311.928867,0.155899,0.138577,0.193385,0.223225,0.002926,0.024425,0.416068,0.191834,148
4,bts,0.639693,0.109827,0.725536,0.144852,-4873.853071,2283.009199,0.108071,0.113135,0.117629,0.162112,0.026800,0.142707,0.513664,0.188043,140

In [ ]:
# apply pca first
song_features = ["Danceability", "Energy", "Loudness", "Speechiness", "Acousticness", "Instrumentalness", "Valence", "Nationality", "Continent","Points (Total)"    ,"detected_languages","num_languages", "language_confidences"]

X= data[song_features].values
print(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

#plot the pca analysis as a scatter plot with artists being different colors
plt.figure(figsize=(10,7))
scatter = plt.scatter(X_pca[:,0], X_pca[:,1], c='blue', alpha=0.5)
plt.title("PCA of Song Features")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid()
plt.show()


# then fit gaussians to the artists

[[0.731 0.573 -10059.0 ... 'SPANISH' 1 'SPANISH: 1.0']
 [0.736 0.802 -4759.0 ... 'ENGLISH' 1 'ENGLISH: 1.0']
 [0.668 0.758 -5176.0 ... 'SPANISH' 1 'SPANISH: 1.0']
 ...
 [0.437 0.716 -4306.0 ... nan 0 nan]
 [0.734 0.607 -7249.0 ... 'ENGLISH' 1 'ENGLISH: 1.0']
 [0.563 0.703 -5756.0 ... nan 0 nan]]

ValueError: could not convert string to float: 'puerto rico'